### PR TITLE
Separation of wing area constraints as submodels 

### PR DESCRIPTION
**Pull request by florentLutz**
Separated the models used for the update on the wing area in 4 submodels : two updates and two constraints. One pair for each type of constraints, here aerodynamic (low speed CL_max) and geometric (enough space to store the fuel inside the wings).
The value of the unit test have not been changed, proof that both method are equivalent in results and the partials that were added have been check with the check_partials() function on the problem created by the run_system inside the unit tests.

### CODE REVIEW

**Review by christophe-david — COMMENTED** [review]
Sorry to process this PR so late 😅 
I'll have very few remarks on the code itself, but the remark about the usage of check_partials makes me wonder if it would be possible to integrate that check in the unit tests.
The result of check_partials looks not so easy to postprocess, but could we think about a way to automate that?

**Comment by florentLutz** [comment]
OpenMDAO does just that with https://openmdao.org/newdocs/versions/latest/features/core_features/working_with_derivatives/unit_testing_partials.html.
I put an example in said test

**Comment by florentLutz** [comment]
Small ajustement: suppressing the out_stream of problem.check_partials() to avoid overloading the actions if this test method is to be generalized

**Review by christophe-david — CHANGES_REQUESTED** [review]
Thank you for this contribution.
The structure is clean and clear. 

Apart the minor change in unit tests, I think that the computation of partials should be done in a more efficient way, because a lot of identical operations are done several times.
I don't know if it would really improve CPU performances, but it would certainly help future maintenance.

**Comment by florentLutz** [comment]
I tried refractoring when it made sense and did not make it harder to understand the derivatives. In the geometric constraints however, to keep the "shape" of the derivatives close to the expression of the value, I "hid" the computation on exponent, hope it's OK

**Review by christophe-david — COMMENTED** [review]
Thanks for the effort at factorizing. That's not what I anticipated, but doing the exercise myself, I wasn't any happier with the result, so let's keep it that way.

The only thing left is a question regarding one of your comments. I would want to have a chat about that.

**Pull request merged**
