### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by esnguyenvan**
Hello,

this pull request for 3 reasons:

- Add load factors in the outputs of cs25.py, as they can be complementary inputs for further structural analysis in pre/post-treatment.
- Fix the unit bug for Vc_eas2.
- Propose to rename a few variables:
Currently two variables, CD:compressibility and CD:trim, are hidden in the outputs.xml because they are written after the vector of drag CD. This is due to the presence of the three following variables:
~CD
~CD:compressibility
~CD:trim
This PR proposes to use explicit naming instead:
~CD
~CD_trim
~CD_compressibility
which leaves all drag terms clearly visible by the user and at the same level as CD0.

### CODE REVIEW

**Comment by christophe-david** [comment]
I am Ok with the first 2 proposed changes, but for the third one, I have doubts: I'm not sure that renaming these variables is a good thing.
This is somehow a breaking change. A minor one, for sure, but a breaking change anyway.
The question to ask in such case is: is the benefit large enough to justify it?
We offer the variable viewer as an alternative to direct editing of the XML files. And the user can still use his editor to get a better presentation (e.g. "Code>Reformat Code" in PyCharm) that will put these 2 variables at a proper location.
We could also think about a way to write the XML files in a more readable way.
On the other hand, the current hierarchy makes sense to me, because compressibility and trim are part of the global CD value. And even more, I realize that our error is that CD0 is on the same level as CD (but I am still not willing to fix that right now, again because I don't think it is worth breaking backward-compatibility).
What do you think?

**Comment by christophe-david** [comment]
I totally agree with that. Thanks!

**Comment by christophe-david** [comment]
(also, I can't believe Visual Code has no XML formatting feature 😉)

**Comment by esnguyenvan** [comment]
Maybe, don't know about it yet :D

**Pull request closed without merging**
